fix: изменить update принимает любое количество полей
Valentina810/lms pull request #100
Opened 2023-10-03 17:50 UTC by Yudiol

2023-10-03 19:32 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
<img width="698" alt="Ты_чево_наделал" src="https://github.com/Valentina810/lms/assets/83814517/9e5d0ad4-935a-4dd8-b522-33692d1c00e7">

2023-10-03 20:02 UTC, Valentina810 requested changes
Мне не нравится, предлагаю или рефлексию или criteriaApi https://github.com/Valentina810/java-explore-with-me/blob/main/ewm-service/src/main/java/ru/practicum/event/dao/EventRepositoryCustomImpl.java

или вот Spring Expression Language (SpEL) - типа безопасен и устойчив к ошибкам

```java
@Service
public class YourEntityService {
    @Autowired
    private YourEntityRepository repository;

    public YourEntity updateEntity(Long entityId, YourEntity updatedEntity) {
        YourEntity existingEntity = repository.findById(entityId)
                .orElseThrow(() -> new EntityNotFoundException("Entity with id " + entityId + " not found"));

        // Используйте SpEL для обновления полей
        SpelExpressionParser parser = new SpelExpressionParser();
        StandardEvaluationContext context = new StandardEvaluationContext(existingEntity);

        if (updatedEntity.getField1() != null) {
            String spelExpression = "field1 = '" + updatedEntity.getField1() + "'";
            parser.parseExpression(spelExpression).getValue(context);
        }

        if (updatedEntity.getField2() != null) {
            String spelExpression = "field2 = '" + updatedEntity.getField2() + "'";
            parser.parseExpression(spelExpression).getValue(context);
        }

        // Продолжайте для других полей...

        return repository.save(existingEntity);
    }
}
```

голосовалку тут можно прикрепить? 

![Кот_не_понял_что_произошло](https://github.com/Valentina810/lms/assets/83814517/db3b07c3-bfe8-4247-96b1-3c6a5546d83a)

2023-10-03 20:02 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/mapper/UpdateUserMapper.java
> +package com.valentinakole.lms.mapper;
не поинтереснее будет?

```java
@Service
public class YourEntityService {
    @Autowired
    private YourEntityRepository repository;

    public YourEntity updateEntity(Long entityId, Map<String, String> updates) {
        YourEntity existingEntity = repository.findById(entityId)
                .orElseThrow(() -> new EntityNotFoundException("Entity with id " + entityId + " not found"));

        updates.forEach((field, value) -> {
            switch (field) {
                case "field1":
                    existingEntity.setField1(value);
                    break;
                case "field2":
                    existingEntity.setField2(value);
                    break;
                case "field3":
                    existingEntity.setField3(value);
                    break;
                case "field4":
                    existingEntity.setField4(value);
                    break;
                case "field5":
                    existingEntity.setField5(value);
                    break;
                default:
                    // Игнорируем неизвестные поля
            }
        });

        return repository.save(existingEntity);
    }
}
```

2023-10-03 20:02 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/mapper/UpdateUserMapper.java
> +    public UserRequestDto toUserRequestDto(User user, UserRequestDto userRequestDto) {
А с рефлексией можно еще компактнее сделать

```java
@Service
public class YourEntityService {
    @Autowired
    private YourEntityRepository repository;

    public YourEntity updateEntity(Long entityId, Map<String, String> updates) {
        YourEntity existingEntity = repository.findById(entityId)
                .orElseThrow(() -> new EntityNotFoundException("Entity with id " + entityId + " not found"));

        try {
            Class<?> entityClass = YourEntity.class;
            Field[] fields = entityClass.getDeclaredFields();

            for (Field field : fields) {
                String fieldName = field.getName();
                if (updates.containsKey(fieldName)) {
                    field.setAccessible(true);
                    field.set(existingEntity, updates.get(fieldName));
                }
            }
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Error updating entity", e);
        }

        return repository.save(existingEntity);
    }
}
```

2023-10-03 20:11 UTC, Yudiol commented
Я по изучая вопрос

2023-10-03 20:31 UTC, Valentina810 commented
Тоже тут оставлю

```java
import org.springframework.beans.BeanUtils;

@RestController
@RequestMapping("/api/entities")
public class YourEntityController {
    @Autowired
    private YourEntityRepository repository;

    @PatchMapping("/{id}")
    public ResponseEntity<YourEntity> updateEntity(@PathVariable Long id, @RequestBody YourEntity updatedEntity) {
        YourEntity existingEntity = repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Entity with id " + id + " not found"));

        // Обновляем только не-null поля из updatedEntity с использованием BeanUtils
        BeanUtils.copyProperties(updatedEntity, existingEntity, getNullPropertyNames(updatedEntity));

        YourEntity savedEntity = repository.save(existingEntity);
        return ResponseEntity.ok(savedEntity);
    }

    private String[] getNullPropertyNames(Object source) {
        final BeanWrapper src = new BeanWrapperImpl(source);
        java.beans.PropertyDescriptor[] pds = src.getPropertyDescriptors();

        Set<String> emptyNames = new HashSet<>();
        for (java.beans.PropertyDescriptor pd : pds) {
            Object srcValue = src.getPropertyValue(pd.getName());
            if (srcValue == null) emptyNames.add(pd.getName());
        }

        String[] result = new String[emptyNames.size()];
        return emptyNames.toArray(result);
    }
}
```

2023-10-06 12:20 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/mapper/UpdateUserMapper.java
> +package com.valentinakole.lms.mapper;
criteriaApi не подойдёт т.к. она может только делать выборки(select) а нам надо обновить(update) данные

2023-10-06 12:30 UTC, Yudiol commented
BeanUtils.copyProperties хорошо , но мне кажется ModelMapper с этой задачей лучше справиться)

2023-10-06 12:31 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
Уже исправил)

2023-10-06 17:11 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/mapper/UpdateUserMapper.java
> +package com.valentinakole.lms.mapper;
Рома, промашка с комментарием, но 
![Нечего_сказать](https://github.com/Valentina810/lms/assets/83814517/8799b71c-1828-4e2f-b294-e61ad5bbc84d)

С другой стороны зато теперь мы это знаем, что тут критерияАпи не подойдёт

2023-10-06 17:12 UTC, Valentina810 commented
Так твое окончательное решение ModelMapper?

<img width="230" alt="Ты" src="https://github.com/Valentina810/lms/assets/83814517/9e9ae827-8a34-4ae7-b18b-b570365f1aa4">

2023-10-06 17:15 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
Рома не шути так больше

![Uploading Я спокоен.png…]()

2023-10-06 18:55 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/mapper/UpdateUserMapper.java
> +package com.valentinakole.lms.mapper;
Здесь лучше подойдёт queryDSL

2023-10-06 19:13 UTC, Yudiol commented
Да , ModelMapper

2023-10-13 19:25 UTC, Valentina810 commented
BeanUtils ставим 5 звезд и предлагаю отклонить этот ПР, в этой ветке нет хорошего решения

2023-10-13 19:25 UTC, closed without merging