fix/controller_update_v2
Valentina810/lms pull request #105
Opened 2023-10-13 07:16 UTC by Yudiol

fix: update user принимает любое кол-во параметров и передаёт то же кол-во в бд

2023-10-13 20:39 UTC, Valentina810 requested changes
Очень много кода. Я чувствую запах костылямбы

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/util/ListPaths.java
> +//
Неиспользуемый код нужно удалять

2023-10-13 20:39 UTC, Valentina810 commented on pom.xml
> +            <version>${querydsl.version}</version>
О, хорошо что вынес версии, всегда так делай 👍

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/repository/UserRepository.java
> +public interface UserRepository extends BaseRepository<User, Long>, QuerydslPredicateExecutor<User> {
Я б лучше наверно сделала отдельный репозитторий, как я тебе в примере показывала

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/util/validation/ValidationEmail.java
> +@RequiredArgsConstructor
Бедные эти классы с валидацией, пошла задачу сделаю на рефакторинг

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/config/WebConfig.java
> +    public ModelMapper modelMapper() {
Вот это номер, это ты из-за Configuration его сюда впихнул?

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/repository/impl/BaseRepositoryImpl.java
> +    protected final QLesson lesson = QLesson.lesson;
😈 Не создавать ненужные сущности без необходимости https://habr.com/ru/companies/itelma/articles/546372/

2023-10-13 20:39 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/service/impl/UserServiceImpl.java
> +    public UserResponseDto update(long userId, Map<String, Object> map){
@RestController
@RequestMapping("/your-entity")
public class YourEntityController {

    private final YourEntityRepository entityRepository;
    private final JPAQueryFactory queryFactory;

    @Autowired
    public YourEntityController(YourEntityRepository entityRepository, EntityManager entityManager) {
        this.entityRepository = entityRepository;
        this.queryFactory = new JPAQueryFactory(entityManager);
    }

    @PatchMapping("/{id}")
    public ResponseEntity<?> updateEntity(@PathVariable Long id, @RequestBody YourEntity update) {
        QYourEntity qEntity = QYourEntity.yourEntity;

        long updated = new JPAUpdateClause(entityManager, qEntity)
            .set(updateField(qEntity.field1, update.getField1()))
            .set(updateField(qEntity.field2, update.getField2()))
            .set(updateField(qEntity.field3, update.getField3()))
            .where(qEntity.id.eq(id))
            .execute();

        if (updated > 0) {
            return ResponseEntity.ok("Обновлено успешно.");
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    private <T> T updateField(Expression<T> field, T value) {
        return value != null ? value : field;
    }
}

2023-10-13 20:53 UTC, Valentina810 commented
```java
@RestController
@RequestMapping("/your-entity")
public class YourEntityController {

    private final YourEntityRepository entityRepository;
    private final JPAQueryFactory queryFactory;

    @Autowired
    public YourEntityController(YourEntityRepository entityRepository, EntityManager entityManager) {
        this.entityRepository = entityRepository;
        this.queryFactory = new JPAQueryFactory(entityManager);
    }

    @PatchMapping("/{id}")
    public ResponseEntity<?> updateEntity(@PathVariable Long id, @RequestBody YourEntity update) {
        QYourEntity qEntity = QYourEntity.yourEntity;

        long updated = new JPAUpdateClause(entityManager, qEntity)
            .set(qEntity.field1, update.getField1() != null ? update.getField1() : qEntity.field1)
            .set(qEntity.field2, update.getField2() != null ? update.getField2() : qEntity.field2)
            .set(qEntity.field3, update.getField3() != null ? update.getField3() : qEntity.field3)
            .where(qEntity.id.eq(id))
            .execute();

        if (updated > 0) {
            return ResponseEntity.ok("Обновлено успешно.");
        } else {
            return ResponseEntity.notFound().build();
        }
    }
}
```

2023-10-13 22:55 UTC, Valentina810 commented
UPDATE your_table
SET
    field1 = CASE WHEN :param_field1 IS NOT NULL THEN :param_field1 ELSE field1 END,
    field2 = CASE WHEN :param_field2 IS NOT NULL THEN :param_field2 ELSE field2 END,
    field3 = CASE WHEN :param_field3 IS NOT NULL THEN :param_field3 ELSE field3 END
WHERE
    your_condition; -- Условие, по которому выбирается запись для обновления

2023-10-14 12:07 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/repository/UserRepository.java
> +public interface UserRepository extends BaseRepository<User, Long>, QuerydslPredicateExecutor<User> {
А что мы с этого выиграем?

2023-10-14 12:07 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/util/validation/ValidationEmail.java
> +@RequiredArgsConstructor
Старую валидацию, а новую оставить

2023-10-14 12:08 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/repository/impl/BaseRepositoryImpl.java
> +    protected final QLesson lesson = QLesson.lesson;
В следующий раз учту

2023-10-14 12:09 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/service/impl/UserServiceImpl.java
> +    public UserResponseDto update(long userId, Map<String, Object> map){
Это не работает

2023-10-15 07:00 UTC, Valentina810 commented
Посмотрела.
Конкретно по твоему решению:
- из хорошего - работает
не понравилось:
- как написано - читается не просто, нет хотя бы пары комментариев зачем как. Логика формирования данных для запросе в сервисе, хотя на мой взгляд, ей место - в репозитории
- метод ListPaths get() - перебирает все поля, даже если у нас пришло одно
- два метода, которые используют рефлексию - есть такое подозрение, что их можно объединить в один, который перебирает только те поля, которые не null
- вот этот вот кусок воообще зачем он? Тут не плохо было задокументировать, написать хоть пару слов почему так
<img width="1066" alt="Снимок экрана 2023-10-15 в 09 56 19" src="https://github.com/Valentina810/lms/assets/83814517/2f8a0798-91b2-470d-99f7-2b38332f7ec8">

Короче попробовала сама, не понравилось, получается типа реализация ради использования QueryDSL, лезть еще в рефлексию. Проще руками просто собрать запрос. Хоть понятно будет что происходит

2023-10-15 07:01 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/repository/UserRepository.java
> +public interface UserRepository extends BaseRepository<User, Long>, QuerydslPredicateExecutor<User> {
Разделим ответственность, упростим чтение кода

2023-10-15 07:02 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/util/validation/ValidationEmail.java
> +@RequiredArgsConstructor
Выкинула это все, сделала валидацию через аннотацию. В следующий раз сразу сделай через аннотацию

2023-10-15 07:07 UTC, Valentina810 commented on src/main/java/com/valentinakole/lms/service/impl/UserServiceImpl.java
> +    public UserResponseDto update(long userId, Map<String, Object> map){
ну увы, платите 20 долларов чтобы работало.
Это ж не обязательно рабочий код, это идеи просто

2023-10-15 07:30 UTC, Valentina810 commented
Всегда ещё думай насколько легко твое решение можно будет расширить. Например, у объекта появилось новое поле типа boolean. Будет твое решение для такого работать? Если нет, много надо исправить для того чтобы работало? Сразу легко разобраться где и что нужно добавить?
Если много надо исправлять или вообще не понятно где чего добавлять значит решение так себе

2023-10-15 15:58 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/util/ListPaths.java
> +//
ок

2023-10-15 16:01 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/repository/UserRepository.java
> +public interface UserRepository extends BaseRepository<User, Long>, QuerydslPredicateExecutor<User> {
Ну не знаю, на одно entity два репозитория делать

2023-10-15 16:07 UTC, Yudiol commented on src/main/java/com/valentinakole/lms/service/impl/UserServiceImpl.java
> +    public UserResponseDto update(long userId, Map<String, Object> map){
Я имел ввиду, сама концепцию, мы хотим что в БД уходили только те поля которые были обновлены, а здесь уходят все поля

2023-10-15 20:04 UTC, Valentina810 commented
Использование рефлексии в Java может быть полезным в определенных случаях, но оно также может быть связано с некоторыми недостатками и проблемами. Вот несколько причин, почему использование рефлексии может быть плохой практикой:

Потенциальные ошибки на этапе компиляции: Рефлексия позволяет вам обращаться к классам, методам и полям динамически, что означает, что многие ошибки, связанные с неправильными именами или типами, будут обнаружены только во время выполнения программы, а не на этапе компиляции. Это может привести к ошибкам, которые сложно обнаружить и исправить.

Низкая производительность: Операции рефлексии обычно медленнее, чем обычные операции с классами и объектами. Это может сказаться на производительности вашей программы, особенно если рефлексию используются внутри циклов или часто вызываются.

Отсутствие проверки доступа: Рефлексия может быть использована для доступа к закрытым методам или полям, что нарушает инкапсуляцию и может привести к неожиданным и нежелательным поведениям.

Увеличенная сложность и поддержка: Использование рефлексии может сделать код более сложным и трудным для понимания и поддержки. Это также может создавать проблемы при обновлении кода или при работе с различными версиями библиотек.

Отсутствие статической проверки типов: При использовании рефлексии компилятор не может проверить правильность типов ваших операций, что может привести к ошибкам во время выполнения.

В целом, рефлексия должна использоваться осторожно и только в случаях, когда другие способы не подходят. Она может быть полезной, например, при разработке инструментов или фреймворков, но ее использование в прикладном коде следует минимизировать. Вместо этого, лучше придерживаться стандартных средств языка и писать код, который легко читать, тестировать и поддерживать.

2023-10-15 20:23 UTC, Yudiol commented
Да я знаю

2023-10-15 21:29 UTC, Valentina810 commented
Отклоняем тогда. Итоговое решение по результатам обсуждений:
так как полей мало, делаем пока через save и BeanUtils.

С уроками будем думать

2023-10-15 21:29 UTC, closed without merging

2023-10-15 21:30 UTC, Valentina810 commented
Предотвращение SQL-инъекций является критически важным аспектом обеспечения безопасности веб-приложений и баз данных. Вот некоторые основные меры, которые помогают предотвратить SQL-инъекции:

Использование параметризованных запросов (Prepared Statements):

Вместо вставки значений непосредственно в SQL-запросы используйте параметризованные запросы, где значения передаются как параметры, а не встраиваются непосредственно в запрос. Это предотвращает SQL-инъекции, так как значения автоматически экранируются и безопасно обрабатываются СУБД.
Использование ORM (Object-Relational Mapping):

ORM-библиотеки, такие как Hibernate, Entity Framework, Django ORM и другие, автоматически генерируют SQL-запросы на основе объектов приложения. Это снижает риск SQL-инъекций, так как библиотеки обычно обеспечивают безопасное формирование SQL-запросов.
Экранирование данных:

Если вы не можете использовать параметризованные запросы, убедитесь, что все вставляемые в SQL-запросы данные экранируются. Экранирование означает, что специальные символы, такие как одинарные кавычки ('), преобразуются в безопасные эквиваленты перед вставкой в запрос.
Ограничение прав доступа:

Применяйте принцип наименьших привилегий, чтобы ограничить права доступа к базе данных. Пользователи и приложения должны иметь только необходимые права на выполнение операций в базе данных.
Валидация входных данных:

Проверяйте и валидируйте все входные данные, включая данные, поступающие от пользователей, чтобы исключить вредоносные или некорректные данные.
Использование Web Application Firewall (WAF):

Веб-приложения могут быть защищены с использованием Web Application Firewall, который может обнаруживать и блокировать попытки SQL-инъекций на уровне сети.
Мониторинг и журналирование:

Ведите журнал запросов к базе данных и мониторьте его на предмет подозрительной активности. Это позволит вовремя обнаруживать и реагировать на потенциальные атаки SQL-инъекций.
Регулярное обновление и обучение персонала:

Обучайте разработчиков и администраторов баз данных по безопасным практикам и обновляйтесь с актуальными угрозами и методами защиты.
Обеспечение безопасности от SQL-инъекций требует комплексного подхода, включая технические и организационные меры.